### Useful Notes
1. Adding cell below: "ALT + Enter" or "Esc + b"
2. Adding cell above: "Esc + a"
3. Running cell: "Shift + Enter"
4. To switch between windows (e.g., PPT and Jupyter): First open the two windows consecutively, then switch between these two windows using "Alt + Tab"
5. Use "#" to include comments.
6. Do not indent (e.g., include spaces at the beginning) when writing codes (except for comments). Indentation is used to structure your code (e.g., functions).
7. Check typos.

# Section 0: Package Check and Importing
An advantage to use Anaconda is that, it has many of the useful packages (e.g., numpy, pandas, matplotlib, scikit-learn,...) installed for us. In below, we try a couple of syntax to see if these packages have been successfully installed. 

In [1]:
# !pip install pandas

In [2]:
import numpy, pandas

In the cells above, we imported two packages/libraries: numpy and pandas. Be aware that we always need to import the packages to apply the corresponding functions/methods. There are two types of imports: general import and selective import.

### Section 0.1: General Import
General imports make all functionality from the package available to you. Just like what we did above, we use **import x** to import package x. More frequently, we use **import xyz as x** to import package xyz, and use abbreviation "x" to refer to "xyz".

In [3]:
import numpy as np
import pandas as pd

### Section 0.2: Selective Import
Instead of loading everything in a package, we can also make the import more selective. For example, we may use only a specific part of a package (e.g., a specific function, a piece of data, a variable, ...) This case, we use: **from A import B**. In here, B is a component of A.

In [4]:
from sklearn.datasets import load_iris
from matplotlib import pyplot as plt

# Section 1: Basic Data Type, Assignment, and Operators

## Section 1.1 Basic data types in Python
 - **int, or integer:** a number without a fractional part. e.g.: 1,2, 100, ...
 - **float, or floating point:** a number that has both an integer and a fractional part, separated by a point. e.g.: 3.14, 5.7, ...
 - **str, or string:** a type to represent text. Use single or double quotes to build a string. e.g.: 'Texas', 'Lucy', ...
 - **bool, or boolean:** a type to represent logical values. Can ONLY be True or False. *Note: No quotation allowed. No abbreviations allowed. Case sensitive.*

We can use the built-in function **type(x)** to obtain the data type for x, if x is a scalar. 



In [6]:
type(3),type(3.14), type('"Hello World!"'), type(True)

(int, float, str, bool)

**Practice:** 

Without running the syntax, answer the questions.
- What is the output of **type('True')** and **type ('3')**?
- What is the output of **type(3.0)**? 
- What is the output of **type(true)**?


In [7]:
type('True'), type ('3'), type(3.0), type(true)

NameError: name 'true' is not defined

## Section 1.2 Assignment
Python variables do not need explicit declaration to reserve memory space. The declaration happens automatically when you assign a value to a variable. Use equal sign (=) to assign values to variables. You can assign a number or a string. Use single or double quotes (i.e., ' ', or " ") for strings.

In [9]:
# Assign an integer:
a = 5
type(a)

int

In [10]:
# Assign a float:
b = 5.9
type(b)

float

In [11]:
int(b)

5

In [12]:
# Assign a string (use '' or "")
name = 'John'
type(name)

str

### Multiple Assignments: 
- You can assign one single value to multiple variables simultaneously. 
- You can also assign multiple different values to different variables simultaneously (more formally, "unpacking"). For multiple-multiple assignment, make sure the dimensions are consistent.

In [13]:
## Assigning one (same) value to multiple variables.
x = y = z = 1 
x,y,z 

(1, 1, 1)

In [14]:
## Assinging multiple values to multiple variables simultaneously.
x, y, z = 7, 4, "Apple" 
x,y,  z

(7, 4, 'Apple')

## Section 1.3 Operators on Numbers
We can apply operators to numbers (i.e., int and float) for naive calculation. Some operators that may be unfamiliar to you are:
- "**": Exponential. (Two multiplication marks)
- "/": Division. After devision, result is float.
- "//": Division. After devision, returns only the integer part.

In [15]:
radius = 2.2

In [16]:
## In below, do some naive calculations
pi = 3.14
area = pi*(radius**2)

In [17]:
## Print the result.  - Use print() function
print(area)

15.197600000000003


In [18]:
print(a)
print(b)

5
5.9


In [19]:
radius = radius + 1

In [20]:
3/2, 3//2

(1.5, 1)

# Section 2: Lists and Numpy Arrays

A list contains items separated by commas and enclosed within square brackets (**[ ]**). In a list, you can store different data types (e.g., string, integer, bool, ...). 

In [21]:
My_list = [3, "Texas", True]

### Section 2.1 List Operators
- The plus (+) sign is the list concatenation operator (i.e., combine two lists). 
- The asterisk (*) is the repetition operator.

In [22]:
Add_list = [123]

In [23]:
## Concatenating
My_list + Add_list

[3, 'Texas', True, 123]

In [24]:
## Repetition
My_list * 3 + Add_list

[3, 'Texas', True, 3, 'Texas', True, 3, 'Texas', True, 123]

### Section 2.1 List Indexing and Slicing
The values stored in a list can be accessed using the slice operator (**[ ]** and **[:]**). 

#### Indexing:
- The length of a list is the number of elements. It can be obtained using built-in function **len(x)**, where x is the list of interest.
- The indices start at **0** in the beginning of the list and work their way to end. The last element can also be obtaned through index len(x) - 1.
- We can also use negative indices, which refers to the position relative to the end. The last element has index: **-1**.


#### Slicing: Use ":"
- **i:j** stands for: From the ith element (include i) to the jth element (not include j)
- If i is not specified, then by default, start from the first element 
- If j is not specified, then by default, end at the last element (inclusive)


In [25]:
# Get the 1st element, last element, 3rd element from My_list.
print(My_list)
print(My_list[0])   # first

print(My_list[2], My_list[-1])  # last


[3, 'Texas', True]
3
True True


In [26]:
# Obtain the 2nd to last element of My_list
print(My_list[1: 3])

# alternative 
print(My_list[1:])

['Texas', True]
['Texas', True]


# Section 3. Numpy
NumPy is the fundamental package for scientific computing with Python. It is great for vector arithmetic. 

In [27]:
# Python List and 1D Numpy Array are similar in terms of indexing and slicing
import numpy as np
x = [1,2,3,4,5] # x is a list
y = np.array(x) # y is a numpy array
print(x[1:3], y[1:3])

[2, 3] [2 3]


If you compare its functionality with regular Python
lists, however, some things have changed.
- Numpy arrays cannot contain elements with different types. If you try to build such an
array, some of the elements' types are changed to end up with a homogeneous list.
- The typical arithmetic operators, such as + and * have a different meaning for regular
Python lists and numpy arrays.
- You can use logic values (True, False) for numpy.

In [28]:
# Example: Numpy array accepts only one type.
x = [1,2,'a', True]
y = np.array(x)
print(y) 

['1' '2' 'a' 'True']


In [29]:
# Example: Arichmetic operators
x = np.array([1,2,3,4,5])
y = [1,2,3,4,5]


x ** 0.5
# y ** 3   TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [30]:
# Example: logic values
my_index = np.array([True, True, False, False, True])
my_index, x, x[my_index]  # logical indexing

(array([ True,  True, False, False,  True]),
 array([1, 2, 3, 4, 5]),
 array([1, 2, 5]))

In [31]:
high = x > 3

x[high]

array([4, 5])

### 2D Numpy Arrays
Consider we have the weight and height of 6 baseball players. The height (in inches) of each player is: 72, 78, 69, 71, 76, 79; and the corresponding weight (in pounds) is: 180, 215, 210, 188, 176, 209.

<img src="Table.png">

In [32]:
## Constructing 2d array
list_2d = [[72,78, 69,71,76, 79],[180, 215, 210, 188, 176, 209]] ## row by row
np_2d = np.array(list_2d)
np_2d

array([[ 72,  78,  69,  71,  76,  79],
       [180, 215, 210, 188, 176, 209]])

In [33]:
# For 2-D array x, x[i,j] represents the ith row and jth column
# Use ":" for slicing. 
## i:j stands for from ith element (include i) to the jth element(not include j)
## if i and j are not specified, then extract all elements

In [34]:
print(np_2d[0:2,0:3])
print(np_2d[:2, :3])
print(np_2d[:,2])
print(np_2d[0,:])

[[ 72  78  69]
 [180 215 210]]
[[ 72  78  69]
 [180 215 210]]
[ 69 210]
[72 78 69 71 76 79]


### Practice
1. Multiply players' weight by 0.454 to convert from pounds to kilograms. Store the resulting numpy array as weight_kg.
2. Use height and weight_kg to calculate the BMI of each player and save the result numpy array as bmi. BMI can be obtained as follows. (Note: 1 meter = 40 inches) 

$$BMI = \frac{weight(kg)}{height(m)^2}$$

3. Report the weight (in kg) of players with bmi greater than 25.
